//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBSAutomation.Locators {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class CustomerLocators : global::System.Configuration.ApplicationSettingsBase {
        
        private static CustomerLocators defaultInstance = ((CustomerLocators)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CustomerLocators())));
        
        public static CustomerLocators Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("subMenuLiCustomers3")]
        public string CustomerMenu_ID {
            get {
                return ((string)(this["CustomerMenu_ID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Create New")]
        public string CreateCustomer_LINK {
            get {
                return ((string)(this["CreateCustomer_LINK"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CustID")]
        public string CustomerID_ID {
            get {
                return ((string)(this["CustomerID_ID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Name")]
        public string CustomerName_ID {
            get {
                return ((string)(this["CustomerName_ID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("autocustomertype")]
        public string CustomerType_ID {
            get {
                return ((string)(this["CustomerType_ID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(//div[@class=\'ui-autocomplete-pagination-results\'])[1]/ul/li[1]/a")]
        public string CustomerTypedropDown_CSS {
            get {
                return ((string)(this["CustomerTypedropDown_CSS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("div.grid-form > fieldset > div > div.center > input.btn")]
        public string CustId_Save_CSS {
            get {
                return ((string)(this["CustId_Save_CSS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CustomerStatusName")]
        public string Customer_Status_ID {
            get {
                return ((string)(this["Customer_Status_ID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Address1_billto_0")]
        public string AddressBillTo_ID {
            get {
                return ((string)(this["AddressBillTo_ID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("City_billto_0")]
        public string CityBillto_ID {
            get {
                return ((string)(this["CityBillto_ID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("State_billto_0")]
        public string BilltoState_ID {
            get {
                return ((string)(this["BilltoState_ID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Zip_billto_0")]
        public string ZipBillto_ID {
            get {
                return ((string)(this["ZipBillto_ID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Country_billto_0")]
        public string CountryBillTo_ID {
            get {
                return ((string)(this["CountryBillTo_ID"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CustomerShortName")]
        public string CustShortname_ID {
            get {
                return ((string)(this["CustShortname_ID"]));
            }
            set {
                this["CustShortname_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Address1_shipto_")]
        public string Shipto_Add_ID {
            get {
                return ((string)(this["Shipto_Add_ID"]));
            }
            set {
                this["Shipto_Add_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("City_shipto_")]
        public string Shipto_City_ID {
            get {
                return ((string)(this["Shipto_City_ID"]));
            }
            set {
                this["Shipto_City_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("State_shipto_")]
        public string Shipto_State_ID {
            get {
                return ((string)(this["Shipto_State_ID"]));
            }
            set {
                this["Shipto_State_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Zip_shipto_")]
        public string ShipTo_Zip_ID {
            get {
                return ((string)(this["ShipTo_Zip_ID"]));
            }
            set {
                this["ShipTo_Zip_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AutoDefShippingMethod")]
        public string Shippingmtd_ID {
            get {
                return ((string)(this["Shippingmtd_ID"]));
            }
            set {
                this["Shippingmtd_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MaxShipOver")]
        public string MaxShipOver_ID {
            get {
                return ((string)(this["MaxShipOver_ID"]));
            }
            set {
                this["MaxShipOver_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ShipMinUnder")]
        public string MinShipOver_ID {
            get {
                return ((string)(this["MinShipOver_ID"]));
            }
            set {
                this["MinShipOver_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("btnSubmit")]
        public string SaveAndClose_ID {
            get {
                return ((string)(this["SaveAndClose_ID"]));
            }
            set {
                this["SaveAndClose_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("btnSave")]
        public string CustSave_ID {
            get {
                return ((string)(this["CustSave_ID"]));
            }
            set {
                this["CustSave_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("filterByName")]
        public string filetrName_ID {
            get {
                return ((string)(this["filetrName_ID"]));
            }
            set {
                this["filetrName_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string table_XPATH {
            get {
                return ((string)(this["table_XPATH"]));
            }
            set {
                this["table_XPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Contacts")]
        public string CustomerContact_LINK {
            get {
                return ((string)(this["CustomerContact_LINK"]));
            }
            set {
                this["CustomerContact_LINK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Contact")]
        public string Contact_ID {
            get {
                return ((string)(this["Contact_ID"]));
            }
            set {
                this["Contact_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ContactPhone")]
        public string ContPh_ID {
            get {
                return ((string)(this["ContPh_ID"]));
            }
            set {
                this["ContPh_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ContactEmail")]
        public string Cont_Email_ID {
            get {
                return ((string)(this["Cont_Email_ID"]));
            }
            set {
                this["Cont_Email_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AutoPrimaryRep")]
        public string PrimaryRep_ID {
            get {
                return ((string)(this["PrimaryRep_ID"]));
            }
            set {
                this["PrimaryRep_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AutoOfficialQuoteRep")]
        public string QouteRep_ID {
            get {
                return ((string)(this["QouteRep_ID"]));
            }
            set {
                this["QouteRep_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#tabCustomerContacts > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > d" +
            "iv.ui-autocomplete-pagination-results > ul.ui-autocomplete.ui-front.ui-menu.ui-w" +
            "idget.ui-widget-content.ui-corner-all > li.ui-menu-item > a.ui-corner-all")]
        public string PrimaryRepDropdown_CSS {
            get {
                return ((string)(this["PrimaryRepDropdown_CSS"]));
            }
            set {
                this["PrimaryRepDropdown_CSS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#tabCustomerContacts > div:nth-child(1) > div:nth-child(2) > div:nth-child(4) > d" +
            "iv.ui-autocomplete-pagination-results > ul.ui-autocomplete.ui-front.ui-menu.ui-w" +
            "idget.ui-widget-content.ui-corner-all > li.ui-menu-item > a.ui-corner-all")]
        public string QouteRepDropDown_CSS {
            get {
                return ((string)(this["QouteRepDropDown_CSS"]));
            }
            set {
                this["QouteRepDropDown_CSS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AutoDefShippingMethod")]
        public string ShippingMtd_CSS {
            get {
                return ((string)(this["ShippingMtd_CSS"]));
            }
            set {
                this["ShippingMtd_CSS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AutoDefUnitizingType")]
        public string CustUntizationPattern_ID {
            get {
                return ((string)(this["CustUntizationPattern_ID"]));
            }
            set {
                this["CustUntizationPattern_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AutoBillingTerms")]
        public string CustBillingTerm_ID {
            get {
                return ((string)(this["CustBillingTerm_ID"]));
            }
            set {
                this["CustBillingTerm_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("div#custTabContent > div.customer-ship-container > div.left-column.grid-form > di" +
            "v > div > div.controls > input#CustomerShortName")]
        public string ShipCustShortName_CSS {
            get {
                return ((string)(this["ShipCustShortName_CSS"]));
            }
            set {
                this["ShipCustShortName_CSS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AutoDefUnitizingType")]
        public string UnitizationType_ID {
            get {
                return ((string)(this["UnitizationType_ID"]));
            }
            set {
                this["UnitizationType_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Country_shipto_")]
        public string CountryShipto_ID {
            get {
                return ((string)(this["CountryShipto_ID"]));
            }
            set {
                this["CountryShipto_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(//div[@class=\'ui-autocomplete-pagination-results\'])[20]/ul/li/a\r\n")]
        public string ShippingMtddropdown_CSS {
            get {
                return ((string)(this["ShippingMtddropdown_CSS"]));
            }
            set {
                this["ShippingMtddropdown_CSS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("liTabUnitizing")]
        public string Unittization_ID {
            get {
                return ((string)(this["Unittization_ID"]));
            }
            set {
                this["Unittization_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Commercial")]
        public string Commercial_LINK {
            get {
                return ((string)(this["Commercial_LINK"]));
            }
            set {
                this["Commercial_LINK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AutoBillingTerms")]
        public string BillingTerms_ID {
            get {
                return ((string)(this["BillingTerms_ID"]));
            }
            set {
                this["BillingTerms_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("div#tabCustomerCommercial > div > div > div.custom-autocomplite-field > div.ui-au" +
            "tocomplete-pagination-results > ul.ui-autocomplete.ui-front.ui-menu.ui-widget.ui" +
            "-widget-content.ui-corner-all > li.ui-menu-item > a.ui-corner-all")]
        public string BillingTermsDropdown_CSS {
            get {
                return ((string)(this["BillingTermsDropdown_CSS"]));
            }
            set {
                this["BillingTermsDropdown_CSS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Make Active")]
        public string Make_Active_LINK {
            get {
                return ((string)(this["Make_Active_LINK"]));
            }
            set {
                this["Make_Active_LINK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("search")]
        public string searchCustomer_ID {
            get {
                return ((string)(this["searchCustomer_ID"]));
            }
            set {
                this["searchCustomer_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("div#gview_list > div.ui-jqgrid-bdiv > div > table#list > tbody > tr:nth-child(2) " +
            "> td:nth-child(2)")]
        public string customerListtable_CSS {
            get {
                return ((string)(this["customerListtable_CSS"]));
            }
            set {
                this["customerListtable_CSS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"list_ShiptoCustomers\"]/tbody/tr[2]/td[1]")]
        public string CustomerDefShipto_ID {
            get {
                return ((string)(this["CustomerDefShipto_ID"]));
            }
            set {
                this["CustomerDefShipto_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("filterByName")]
        public string filterByName_ID {
            get {
                return ((string)(this["filterByName_ID"]));
            }
            set {
                this["filterByName_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AutoBusinessDiscount")]
        public string AutoBusinessDiscount_ID {
            get {
                return ((string)(this["AutoBusinessDiscount_ID"]));
            }
            set {
                this["AutoBusinessDiscount_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("div#tabContentUnitizing > div#tabUnitizing > div > div.custom-autocomplite-field " +
            "> div.controls > div.ui-autocomplete-pagination-results > ul.ui-autocomplete.ui-" +
            "front.ui-menu.ui-widget.ui-widget-content.ui-corner-all > li.ui-menu-item > a.ui" +
            "-corner-all")]
        public string Untitypedropdown_CSS {
            get {
                return ((string)(this["Untitypedropdown_CSS"]));
            }
            set {
                this["Untitypedropdown_CSS"] = value;
            }
        }
    }
}
