//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBSAutomation.Locators {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class GeneralProperties : global::System.Configuration.ApplicationSettingsBase {
        
        private static GeneralProperties defaultInstance = ((GeneralProperties)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new GeneralProperties())));
        
        public static GeneralProperties Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://crs1-bawcti04/CBSMaster")]
        public string BASEURL1 {
            get {
                return ((string)(this["BASEURL1"]));
            }
            set {
                this["BASEURL1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("chrome")]
        public string BROWSER {
            get {
                return ((string)(this["BROWSER"]));
            }
            set {
                this["BROWSER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\GitCBS\\cti-pbs\\DEV\\NET4\\SeleniumAutomation\\CBSAutomation\\CBSAutomation\\ExcelIO" +
            "\\CBSInputTestData.xls")]
        public string FILEPATH1 {
            get {
                return ((string)(this["FILEPATH1"]));
            }
            set {
                this["FILEPATH1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\ExcelTotest")]
        public string FILE {
            get {
                return ((string)(this["FILE"]));
            }
            set {
                this["FILE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://crs1-bawcti04/CBSnew")]
        public string url {
            get {
                return ((string)(this["url"]));
            }
            set {
                this["url"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://crs1-bawcti03/CBS")]
        public string BASEURL {
            get {
                return ((string)(this["BASEURL"]));
            }
            set {
                this["BASEURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\GitCBS\\cti-pbs\\DEV\\NET4\\SeleniumAutomation\\CBSAutomation\\CBSAutomation\\ExcelIO" +
            "\\CBSInputTestDataPostgress.xls")]
        public string FILEPATH {
            get {
                return ((string)(this["FILEPATH"]));
            }
            set {
                this["FILEPATH"] = value;
            }
        }
    }
}
