//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBSAutomation.Locators {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Material : global::System.Configuration.ApplicationSettingsBase {
        
        private static Material defaultInstance = ((Material)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Material())));
        
        public static Material Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting {
            get {
                return ((string)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("menuLIPurchasing2")]
        public string PruchasingMenu_ID {
            get {
                return ((string)(this["PruchasingMenu_ID"]));
            }
            set {
                this["PruchasingMenu_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("subMenuLiMaterials7")]
        public string MatrerialMenu_ID {
            get {
                return ((string)(this["MatrerialMenu_ID"]));
            }
            set {
                this["MatrerialMenu_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("createNew")]
        public string CreateNewmaterial_ID {
            get {
                return ((string)(this["CreateNewmaterial_ID"]));
            }
            set {
                this["CreateNewmaterial_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MaterialID")]
        public string Materail_ID {
            get {
                return ((string)(this["Materail_ID"]));
            }
            set {
                this["Materail_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MaterialDescription")]
        public string MaterialDescription_ID {
            get {
                return ((string)(this["MaterialDescription_ID"]));
            }
            set {
                this["MaterialDescription_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ddlMaterialTypeLink")]
        public string MaterialType_ID {
            get {
                return ((string)(this["MaterialType_ID"]));
            }
            set {
                this["MaterialType_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CostCurrent")]
        public string CostCurrent_ID {
            get {
                return ((string)(this["CostCurrent_ID"]));
            }
            set {
                this["CostCurrent_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IsRealMaterial")]
        public string IsRealMaterial_ID {
            get {
                return ((string)(this["IsRealMaterial_ID"]));
            }
            set {
                this["IsRealMaterial_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("filterByMaterialID")]
        public string FilterMateriall1_ID {
            get {
                return ((string)(this["FilterMateriall1_ID"]));
            }
            set {
                this["FilterMateriall1_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("search")]
        public string filter_ID {
            get {
                return ((string)(this["filter_ID"]));
            }
            set {
                this["filter_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".btn.btn-primary")]
        public string Save_CSS {
            get {
                return ((string)(this["Save_CSS"]));
            }
            set {
                this["Save_CSS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ddlStockedItem")]
        public string StockedItem_ID {
            get {
                return ((string)(this["StockedItem_ID"]));
            }
            set {
                this["StockedItem_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"list\"]/tbody/tr[2]/td[4]")]
        public string Activestatus_XPATH {
            get {
                return ((string)(this["Activestatus_XPATH"]));
            }
            set {
                this["Activestatus_XPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("filterByMaterialID")]
        public string FilterMaterial_ID {
            get {
                return ((string)(this["FilterMaterial_ID"]));
            }
            set {
                this["FilterMaterial_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//div[@id=\"list\"]/tbody/tr[2]/td[2]")]
        public string Material_table_XPATH {
            get {
                return ((string)(this["Material_table_XPATH"]));
            }
            set {
                this["Material_table_XPATH"] = value;
            }
        }
    }
}
