//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBSAutomation.Locators {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Orders : global::System.Configuration.ApplicationSettingsBase {
        
        private static Orders defaultInstance = ((Orders)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Orders())));
        
        public static Orders Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("menuLIOrderManagement1")]
        public string orderManag_ID {
            get {
                return ((string)(this["orderManag_ID"]));
            }
            set {
                this["orderManag_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("subMenuLiOrderentry1")]
        public string Orderentry_ID {
            get {
                return ((string)(this["Orderentry_ID"]));
            }
            set {
                this["Orderentry_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bill-to-customer-id")]
        public string ordercustomer_ID {
            get {
                return ((string)(this["ordercustomer_ID"]));
            }
            set {
                this["ordercustomer_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"quick-order-entry-container\"]/table/tbody/tr[1]/td/div[1]/div/div/ul/li/" +
            "a")]
        public string dropdown_XPATH {
            get {
                return ((string)(this["dropdown_XPATH"]));
            }
            set {
                this["dropdown_XPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"quick-order-entry-container\"]/table/tbody/tr[2]/td/table")]
        public string ordertable_XPATH {
            get {
                return ((string)(this["ordertable_XPATH"]));
            }
            set {
                this["ordertable_XPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"quick-order-entry-container\"]/table/tbody/tr[2]/td/table/tbody/tr/td[2]/" +
            "input")]
        public string ordernetryPO_XPATH {
            get {
                return ((string)(this["ordernetryPO_XPATH"]));
            }
            set {
                this["ordernetryPO_XPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"quick-order-entry-container\"]/table/tbody/tr[2]/td/table/tbody/tr/td[4]/" +
            "div/input")]
        public string Shipto_XPATH {
            get {
                return ((string)(this["Shipto_XPATH"]));
            }
            set {
                this["Shipto_XPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(//div[@class=\'ui-autocomplete-pagination-results\'])[2]/ul/li/a")]
        public string ShipToDropDown_XPATH {
            get {
                return ((string)(this["ShipToDropDown_XPATH"]));
            }
            set {
                this["ShipToDropDown_XPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"quick-order-entry-container\"]/table/tbody/tr[2]/td/table/tbody/tr/td[7]/" +
            "div/input")]
        public string DileverySpec_XPATH {
            get {
                return ((string)(this["DileverySpec_XPATH"]));
            }
            set {
                this["DileverySpec_XPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(//div[@class=\'ui-autocomplete-pagination-results\'])[3]/ul/li/a")]
        public string DileverySpecdropdown_XPATH {
            get {
                return ((string)(this["DileverySpecdropdown_XPATH"]));
            }
            set {
                this["DileverySpecdropdown_XPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"quick-order-entry-container\"]/table/tbody/tr[2]/td/table/tbody/tr/td[8]/" +
            "input")]
        public string orderQty_XPATH {
            get {
                return ((string)(this["orderQty_XPATH"]));
            }
            set {
                this["orderQty_XPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"quick-order-entry-container\"]/table/tbody/tr[2]/td/table/tbody/tr/td[10]" +
            "/input")]
        public string OrderDueDate_XPATH {
            get {
                return ((string)(this["OrderDueDate_XPATH"]));
            }
            set {
                this["OrderDueDate_XPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"quick-order-entry-container\"]/table/tbody/tr[2]/td/table/tbody/tr/td[12]" +
            "/input")]
        public string OrderDueDatePrice_XPATH {
            get {
                return ((string)(this["OrderDueDatePrice_XPATH"]));
            }
            set {
                this["OrderDueDatePrice_XPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"quick-order-entry-container\"]/div/a[2]")]
        public string OrderSave_XPATH {
            get {
                return ((string)(this["OrderSave_XPATH"]));
            }
            set {
                this["OrderSave_XPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ui-datepicker-div")]
        public string OrderdatePicker_ID {
            get {
                return ((string)(this["OrderdatePicker_ID"]));
            }
            set {
                this["OrderdatePicker_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"sales-orders\"]/tbody/tr[2]/td[7]/a")]
        public string OrderId_XPATH {
            get {
                return ((string)(this["OrderId_XPATH"]));
            }
            set {
                this["OrderId_XPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ddlProductBoardSupplier")]
        public string supplier_ID {
            get {
                return ((string)(this["supplier_ID"]));
            }
            set {
                this["supplier_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"quick-order-entry-container\"]/div[1]/a[1]")]
        public string AddSalesLine_XPATH {
            get {
                return ((string)(this["AddSalesLine_XPATH"]));
            }
            set {
                this["AddSalesLine_XPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("save_btn")]
        public string SaveOrder_ID {
            get {
                return ((string)(this["SaveOrder_ID"]));
            }
            set {
                this["SaveOrder_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("form#quick-order-entry-container.grid-form > div.control-group > a.btn.btn-succes" +
            "s")]
        public string AddSalesLine_CSS {
            get {
                return ((string)(this["AddSalesLine_CSS"]));
            }
            set {
                this["AddSalesLine_CSS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"quick-order-entry-container\"]/table/tbody/tr[2]/td/table/tbody/tr[2]/td[" +
            "7]/div/input")]
        public string DileverySpecLine2_XPATH {
            get {
                return ((string)(this["DileverySpecLine2_XPATH"]));
            }
            set {
                this["DileverySpecLine2_XPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"quick-order-entry-container\"]/table/tbody/tr[2]/td/table/tbody/tr[2]/td[" +
            "8]/input")]
        public string orderQtyLine2_XPATH {
            get {
                return ((string)(this["orderQtyLine2_XPATH"]));
            }
            set {
                this["orderQtyLine2_XPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"quick-order-entry-container\"]/table/tbody/tr[2]/td/table/tbody/tr[2]/td[" +
            "10]/input")]
        public string OrderDueDateLine2_XPATH {
            get {
                return ((string)(this["OrderDueDateLine2_XPATH"]));
            }
            set {
                this["OrderDueDateLine2_XPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(//div[@class=\'ui-autocomplete-pagination-results\'])[5]/ul/li/a")]
        public string DileverySpecdropdownLine2_XPATH {
            get {
                return ((string)(this["DileverySpecdropdownLine2_XPATH"]));
            }
            set {
                this["DileverySpecdropdownLine2_XPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("div#order-grid-container > div.grid-scroll-wrapper > div#gbox_sales-orders > div#" +
            "gview_sales-orders > div.ui-jqgrid-bdiv > div > table#sales-orders > tbody > tr:" +
            "nth-child(2) > td:nth-child(7)> a.underline")]
        public string OrderList_CSS {
            get {
                return ((string)(this["OrderList_CSS"]));
            }
            set {
                this["OrderList_CSS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("filter-by-order-id")]
        public string filterbyorder_ID {
            get {
                return ((string)(this["filterbyorder_ID"]));
            }
            set {
                this["filterbyorder_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(//div[@class=\'ui-autocomplete-pagination-results\'])[1]/ul/li[1]/a")]
        public string FilterOrderDropdown_XPATH {
            get {
                return ((string)(this["FilterOrderDropdown_XPATH"]));
            }
            set {
                this["FilterOrderDropdown_XPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("filter-sale-lines")]
        public string filtersalelines_ID {
            get {
                return ((string)(this["filtersalelines_ID"]));
            }
            set {
                this["filtersalelines_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"sales-orders\"]/tbody/tr[2]/td[14]/a")]
        public string orderTableList_XPATH {
            get {
                return ((string)(this["orderTableList_XPATH"]));
            }
            set {
                this["orderTableList_XPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("subMenuLiOrders0")]
        public string subMenuLiOrders_ID {
            get {
                return ((string)(this["subMenuLiOrders_ID"]));
            }
            set {
                this["subMenuLiOrders_ID"] = value;
            }
        }
    }
}
