//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBSAutomation.Locators {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class PayableReceipts : global::System.Configuration.ApplicationSettingsBase {
        
        private static PayableReceipts defaultInstance = ((PayableReceipts)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PayableReceipts())));
        
        public static PayableReceipts Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("menuLIAccounting3")]
        public string AcountingMenu_ID {
            get {
                return ((string)(this["AcountingMenu_ID"]));
            }
            set {
                this["AcountingMenu_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("subMenuLiPayableReceipts3")]
        public string Payablereceipts_ID {
            get {
                return ((string)(this["Payablereceipts_ID"]));
            }
            set {
                this["Payablereceipts_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("filterByCustPO")]
        public string FilterByPOid_ID {
            get {
                return ((string)(this["FilterByPOid_ID"]));
            }
            set {
                this["FilterByPOid_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("filterByReceiptTypes")]
        public string TypeOfreceipt_ID {
            get {
                return ((string)(this["TypeOfreceipt_ID"]));
            }
            set {
                this["TypeOfreceipt_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("filterByCustomer")]
        public string filterByCustomer_ID {
            get {
                return ((string)(this["filterByCustomer_ID"]));
            }
            set {
                this["filterByCustomer_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("search")]
        public string SerachReceipt_ID {
            get {
                return ((string)(this["SerachReceipt_ID"]));
            }
            set {
                this["SerachReceipt_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vendor-selector")]
        public string VendorIDReceipt_ID {
            get {
                return ((string)(this["VendorIDReceipt_ID"]));
            }
            set {
                this["VendorIDReceipt_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("invoice-date")]
        public string InvoiceDate_ID {
            get {
                return ((string)(this["InvoiceDate_ID"]));
            }
            set {
                this["InvoiceDate_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("payable-start")]
        public string Beginpayable_ID {
            get {
                return ((string)(this["Beginpayable_ID"]));
            }
            set {
                this["Beginpayable_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("list_Payables")]
        public string receiptTable_ID {
            get {
                return ((string)(this["receiptTable_ID"]));
            }
            set {
                this["receiptTable_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("payable-complete-button")]
        public string CompletePay_ID {
            get {
                return ((string)(this["CompletePay_ID"]));
            }
            set {
                this["CompletePay_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(//div[@class=\'ui-autocomplete-pagination-results\'])[3]/ul/li[1]/a")]
        public string PayableCustomerDropdown_XPATH {
            get {
                return ((string)(this["PayableCustomerDropdown_XPATH"]));
            }
            set {
                this["PayableCustomerDropdown_XPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(//div[@class=\'ui-autocomplete-pagination-results\'])[2]/ul/li[1]/a")]
        public string PayableDropdown_XPATH {
            get {
                return ((string)(this["PayableDropdown_XPATH"]));
            }
            set {
                this["PayableDropdown_XPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("filterByStatus")]
        public string filterByStatus_ID {
            get {
                return ((string)(this["filterByStatus_ID"]));
            }
            set {
                this["filterByStatus_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"list_Payables\"]/tbody/tr[2]/td[6]")]
        public string POvalue_XPATH {
            get {
                return ((string)(this["POvalue_XPATH"]));
            }
            set {
                this["POvalue_XPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("filterByReceiptNumber")]
        public string PayablereceiptsSearch_ID {
            get {
                return ((string)(this["PayablereceiptsSearch_ID"]));
            }
            set {
                this["PayablereceiptsSearch_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//table[@id=\'list_Payables\']/tbody/tr[2]")]
        public string ReceiptTable_XPATH {
            get {
                return ((string)(this["ReceiptTable_XPATH"]));
            }
            set {
                this["ReceiptTable_XPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("save-payable")]
        public string SavePayable_ID {
            get {
                return ((string)(this["SavePayable_ID"]));
            }
            set {
                this["SavePayable_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("close-batch")]
        public string closebatchReceipt_ID {
            get {
                return ((string)(this["closebatchReceipt_ID"]));
            }
            set {
                this["closebatchReceipt_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("filterByCustPO")]
        public string FilterByPO_ID {
            get {
                return ((string)(this["FilterByPO_ID"]));
            }
            set {
                this["FilterByPO_ID"] = value;
            }
        }
    }
}
