//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBSAutomation.Locators {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class POProcessing : global::System.Configuration.ApplicationSettingsBase {
        
        private static POProcessing defaultInstance = ((POProcessing)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new POProcessing())));
        
        public static POProcessing Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("menuLIAccounting3")]
        public string AccountingMenu_ID {
            get {
                return ((string)(this["AccountingMenu_ID"]));
            }
            set {
                this["AccountingMenu_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("subMenuLiPOProcessing2")]
        public string POProcessing_ID {
            get {
                return ((string)(this["POProcessing_ID"]));
            }
            set {
                this["POProcessing_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("filter-by-processingPOviewmodes")]
        public string FilterTool_ID {
            get {
                return ((string)(this["FilterTool_ID"]));
            }
            set {
                this["FilterTool_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("search")]
        public string FilterPO_ID {
            get {
                return ((string)(this["FilterPO_ID"]));
            }
            set {
                this["FilterPO_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"tools-grid\"]/tbody/tr[2]/td[1]/input")]
        public string Table_toolgrid_XPATH {
            get {
                return ((string)(this["Table_toolgrid_XPATH"]));
            }
            set {
                this["Table_toolgrid_XPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("process-po")]
        public string ProcessPO_ID {
            get {
                return ((string)(this["ProcessPO_ID"]));
            }
            set {
                this["ProcessPO_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"tools-grid\"]/tbody/tr[2]/td[9]")]
        public string POstatus_XPATH {
            get {
                return ((string)(this["POstatus_XPATH"]));
            }
            set {
                this["POstatus_XPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("filter-by-order-ID")]
        public string FilterOrderid_ID {
            get {
                return ((string)(this["FilterOrderid_ID"]));
            }
            set {
                this["FilterOrderid_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("print-po-report")]
        public string PrintOrderPOReport_ID {
            get {
                return ((string)(this["PrintOrderPOReport_ID"]));
            }
            set {
                this["PrintOrderPOReport_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"tools-grid\"]/tbody/tr[2]/td[5]")]
        public string ProcessPOID_XPATH {
            get {
                return ((string)(this["ProcessPOID_XPATH"]));
            }
            set {
                this["ProcessPOID_XPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("filter-by-material-ID")]
        public string FilterByMaterial_ID {
            get {
                return ((string)(this["FilterByMaterial_ID"]));
            }
            set {
                this["FilterByMaterial_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"po-grid\"]/tbody/tr[2]/td[2]/input")]
        public string Material_toolgrid_XPATH {
            get {
                return ((string)(this["Material_toolgrid_XPATH"]));
            }
            set {
                this["Material_toolgrid_XPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"po-grid\"]/tbody/tr[2]/td[6]")]
        public string MaterialProcessPOID_XPATH {
            get {
                return ((string)(this["MaterialProcessPOID_XPATH"]));
            }
            set {
                this["MaterialProcessPOID_XPATH"] = value;
            }
        }
    }
}
