//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBSAutomation.Locators {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class PurchaseBoard : global::System.Configuration.ApplicationSettingsBase {
        
        private static PurchaseBoard defaultInstance = ((PurchaseBoard)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PurchaseBoard())));
        
        public static PurchaseBoard Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("filter-by-order-id")]
        public string PrucaseboardOrderID_ID {
            get {
                return ((string)(this["PrucaseboardOrderID_ID"]));
            }
            set {
                this["PrucaseboardOrderID_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("search")]
        public string PurchaseBoardSearch_ID {
            get {
                return ((string)(this["PurchaseBoardSearch_ID"]));
            }
            set {
                this["PurchaseBoardSearch_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"purchase-orders\"]/tbody/tr[2]/td")]
        public string BoardList_XPATH {
            get {
                return ((string)(this["BoardList_XPATH"]));
            }
            set {
                this["BoardList_XPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("suppliers-for-grade")]
        public string BoardList_ID {
            get {
                return ((string)(this["BoardList_ID"]));
            }
            set {
                this["BoardList_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"order-group-detail-grid\"]/tbody/tr[2]/td[2]")]
        public string BoardListOrder_XPATH {
            get {
                return ((string)(this["BoardListOrder_XPATH"]));
            }
            set {
                this["BoardListOrder_XPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#right-column > #order-group-detail > #order-group-detail-grid > tbody > tr.group" +
            "-footer > td.generate-po > input.btn-mini.btn-success.create-po")]
        public string CreateBoardPO_CSS {
            get {
                return ((string)(this["CreateBoardPO_CSS"]));
            }
            set {
                this["CreateBoardPO_CSS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("goto-board-po-processing")]
        public string BoardProcessPO_ID {
            get {
                return ((string)(this["BoardProcessPO_ID"]));
            }
            set {
                this["BoardProcessPO_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("best-price-detail")]
        public string BestPriceSupplier_ID {
            get {
                return ((string)(this["BestPriceSupplier_ID"]));
            }
            set {
                this["BestPriceSupplier_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#best-price-detail > #suppliers-for-grade-container > #suppliers-for-grade > tbod" +
            "y > tr:nth-child(1)")]
        public string BoradSupplier_CSS {
            get {
                return ((string)(this["BoradSupplier_CSS"]));
            }
            set {
                this["BoradSupplier_CSS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("subMenuLiPurchaseBoard0")]
        public string PurcahseboardMenu_ID {
            get {
                return ((string)(this["PurcahseboardMenu_ID"]));
            }
            set {
                this["PurcahseboardMenu_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"po-grid\"]/tbody/tr[2]/td[2]")]
        public string selectBoadPrint_XPATH {
            get {
                return ((string)(this["selectBoadPrint_XPATH"]));
            }
            set {
                this["selectBoadPrint_XPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"po-grid\"]/tbody/tr[2]/td[6]")]
        public string selectBoadPOValue_XPATH {
            get {
                return ((string)(this["selectBoadPOValue_XPATH"]));
            }
            set {
                this["selectBoadPOValue_XPATH"] = value;
            }
        }
    }
}
