//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBSAutomation.Locators {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class PurchaseMaterial : global::System.Configuration.ApplicationSettingsBase {
        
        private static PurchaseMaterial defaultInstance = ((PurchaseMaterial)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PurchaseMaterial())));
        
        public static PurchaseMaterial Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("createNewPO")]
        public string CreatePOMaterial_ID {
            get {
                return ((string)(this["CreatePOMaterial_ID"]));
            }
            set {
                this["CreatePOMaterial_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("supplier-autocomplete")]
        public string Supplier_ID {
            get {
                return ((string)(this["Supplier_ID"]));
            }
            set {
                this["Supplier_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("warehouse-list")]
        public string Warehouse_ID {
            get {
                return ((string)(this["Warehouse_ID"]));
            }
            set {
                this["Warehouse_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("transportmode-list")]
        public string TrasportMode_ID {
            get {
                return ((string)(this["TrasportMode_ID"]));
            }
            set {
                this["TrasportMode_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("find-materials")]
        public string SelectMaterial_ID {
            get {
                return ((string)(this["SelectMaterial_ID"]));
            }
            set {
                this["SelectMaterial_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(//div[@class=\'ui-autocomplete-pagination-results\'])[2]/ul/li[1]/a")]
        public string MaterialSupplierDropdown_XPATH {
            get {
                return ((string)(this["MaterialSupplierDropdown_XPATH"]));
            }
            set {
                this["MaterialSupplierDropdown_XPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(//div[@class=\'ui-autocomplete-pagination-results\'])[1]/ul/li[1]/a")]
        public string WarehousDropdown_XPATH {
            get {
                return ((string)(this["WarehousDropdown_XPATH"]));
            }
            set {
                this["WarehousDropdown_XPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(//div[@class=\'ui-autocomplete-pagination-results\'])[3]/ul/li[1]/a")]
        public string TrasportModeDropdown_XPATH {
            get {
                return ((string)(this["TrasportModeDropdown_XPATH"]));
            }
            set {
                this["TrasportModeDropdown_XPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("div#search-materials-dialog > fieldset > div > div.enableControlForReadAccess > d" +
            "iv > input#filter-by-material-ID")]
        public string MaterialIDSearch_CSS {
            get {
                return ((string)(this["MaterialIDSearch_CSS"]));
            }
            set {
                this["MaterialIDSearch_CSS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("div#search-materials-dialog > fieldset > div > div.enableControlForReadAccess > d" +
            "iv.center > a#search")]
        public string MaterialFilter_CSS {
            get {
                return ((string)(this["MaterialFilter_CSS"]));
            }
            set {
                this["MaterialFilter_CSS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("div#search-materials-dialog > div.modal-body > div#gbox_material-search-grid > di" +
            "v#gview_material-search-grid > div.ui-jqgrid-bdiv > div > table#material-search-" +
            "grid > tbody > tr:nth-child(2) > td:nth-child(1) > input")]
        public string MaterialSelectCheckbox_CSS {
            get {
                return ((string)(this["MaterialSelectCheckbox_CSS"]));
            }
            set {
                this["MaterialSelectCheckbox_CSS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("add-material-po-line")]
        public string AddMaterialPO_ID {
            get {
                return ((string)(this["AddMaterialPO_ID"]));
            }
            set {
                this["AddMaterialPO_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("save-po-button")]
        public string SavePO_ID {
            get {
                return ((string)(this["SavePO_ID"]));
            }
            set {
                this["SavePO_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("menuLIPurchasing2")]
        public string PurcahsingMenu_ID {
            get {
                return ((string)(this["PurcahsingMenu_ID"]));
            }
            set {
                this["PurcahsingMenu_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("subMenuLiPurchaseMaterials1")]
        public string PurchaseMaterial_ID {
            get {
                return ((string)(this["PurchaseMaterial_ID"]));
            }
            set {
                this["PurchaseMaterial_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("filter-by-viewmodes")]
        public string MaterialMode_ID {
            get {
                return ((string)(this["MaterialMode_ID"]));
            }
            set {
                this["MaterialMode_ID"] = value;
            }
        }
    }
}
