//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBSAutomation.Locators {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class QuotationProperty : global::System.Configuration.ApplicationSettingsBase {
        
        private static QuotationProperty defaultInstance = ((QuotationProperty)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new QuotationProperty())));
        
        public static QuotationProperty Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("customer")]
        public string CuatomerName_ID {
            get {
                return ((string)(this["CuatomerName_ID"]));
            }
            set {
                this["CuatomerName_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Salutation")]
        public string Salutation_ID {
            get {
                return ((string)(this["Salutation_ID"]));
            }
            set {
                this["Salutation_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("QuotationBusinessStatus")]
        public string QuotationBusinessStatus_ID {
            get {
                return ((string)(this["QuotationBusinessStatus_ID"]));
            }
            set {
                this["QuotationBusinessStatus_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("QuotationApprovedStatus")]
        public string QuotationApprovedStatus_ID {
            get {
                return ((string)(this["QuotationApprovedStatus_ID"]));
            }
            set {
                this["QuotationApprovedStatus_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("QuotationEffectiveStartDate")]
        public string QuotationEffectiveStartDate_ID {
            get {
                return ((string)(this["QuotationEffectiveStartDate_ID"]));
            }
            set {
                this["QuotationEffectiveStartDate_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("find-quotation-estimate-prices")]
        public string findquotationestimateprices_ID {
            get {
                return ((string)(this["findquotationestimateprices_ID"]));
            }
            set {
                this["findquotationestimateprices_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("filterBySpecId")]
        public string filterBySpecId_ID {
            get {
                return ((string)(this["filterBySpecId_ID"]));
            }
            set {
                this["filterBySpecId_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("estimates-search-filter")]
        public string estimatessearchfilter_ID {
            get {
                return ((string)(this["estimatessearchfilter_ID"]));
            }
            set {
                this["estimatessearchfilter_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//table[@id=\"estimate-search-grid\"]/tbody/tr[2]/td[1]/input\r\n")]
        public string Tablelist_XPATH {
            get {
                return ((string)(this["Tablelist_XPATH"]));
            }
            set {
                this["Tablelist_XPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("add-quotation-estimates")]
        public string addquotationestimates_ID {
            get {
                return ((string)(this["addquotationestimates_ID"]));
            }
            set {
                this["addquotationestimates_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//table[@id=\"quotation-estimate-price-grid\"]/tbody/tr[2]/td[3]\r\n")]
        public string MainTableList_XPATH {
            get {
                return ((string)(this["MainTableList_XPATH"]));
            }
            set {
                this["MainTableList_XPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("div.control-group")]
        public string Save_Link {
            get {
                return ((string)(this["Save_Link"]));
            }
            set {
                this["Save_Link"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("print-button")]
        public string QuotationReport_ID {
            get {
                return ((string)(this["QuotationReport_ID"]));
            }
            set {
                this["QuotationReport_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("subMenuLiQuotations1")]
        public string quotationMenuLInk_ID {
            get {
                return ((string)(this["quotationMenuLInk_ID"]));
            }
            set {
                this["quotationMenuLInk_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Create New")]
        public string Create_New_LINK {
            get {
                return ((string)(this["Create_New_LINK"]));
            }
            set {
                this["Create_New_LINK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#search-quotation-dialog > div.modal-footer > #add-quotation-estimates\r\n")]
        public string searchquotationdialog_CSS {
            get {
                return ((string)(this["searchquotationdialog_CSS"]));
            }
            set {
                this["searchquotationdialog_CSS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(//div[@class=\'ui-autocomplete-pagination-results\'])[1]/ul/li[1]/a")]
        public string CustomerSelectDropdown_XPATH {
            get {
                return ((string)(this["CustomerSelectDropdown_XPATH"]));
            }
            set {
                this["CustomerSelectDropdown_XPATH"] = value;
            }
        }
    }
}
