//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBSAutomation.Locators {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class RecevingPO : global::System.Configuration.ApplicationSettingsBase {
        
        private static RecevingPO defaultInstance = ((RecevingPO)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new RecevingPO())));
        
        public static RecevingPO Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("subMenuLiPOReceiptEntry4")]
        public string POReceving_ID {
            get {
                return ((string)(this["POReceving_ID"]));
            }
            set {
                this["POReceving_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("supplier-id")]
        public string receiveSpplier_ID {
            get {
                return ((string)(this["receiveSpplier_ID"]));
            }
            set {
                this["receiveSpplier_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("receive-board")]
        public string ReceiveBoard_ID {
            get {
                return ((string)(this["ReceiveBoard_ID"]));
            }
            set {
                this["ReceiveBoard_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("shippmentId")]
        public string Shipment_ID {
            get {
                return ((string)(this["Shipment_ID"]));
            }
            set {
                this["Shipment_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#quick-receipt-entry-container > div.control-group > a:nth-child(1)")]
        public string AddRecepietLine_CSS {
            get {
                return ((string)(this["AddRecepietLine_CSS"]));
            }
            set {
                this["AddRecepietLine_CSS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("form#quick-receipt-entry-container > table.ko-grid.styled-ko-grid > tbody > tr:nt" +
            "h-child(1) > td:nth-child(1) > div.custom-autocomplite-field > input")]
        public string POinputReceive_CSS {
            get {
                return ((string)(this["POinputReceive_CSS"]));
            }
            set {
                this["POinputReceive_CSS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("form#quick-receipt-entry-container > table.ko-grid.styled-ko-grid > tbody > tr:nt" +
            "h-child(1) > td:nth-child(5) > input")]
        public string ReceiveUnit_ID {
            get {
                return ((string)(this["ReceiveUnit_ID"]));
            }
            set {
                this["ReceiveUnit_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("form#quick-receipt-entry-container > table.ko-grid.styled-ko-grid > tbody > tr:nt" +
            "h-child(1) > td:nth-child(6) > input")]
        public string UnitQty_ID {
            get {
                return ((string)(this["UnitQty_ID"]));
            }
            set {
                this["UnitQty_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("form#quick-receipt-entry-container > table.ko-grid.styled-ko-grid > tbody > tr:nt" +
            "h-child(1) > td:nth-child(7) > input")]
        public string LatUnitQty_ID {
            get {
                return ((string)(this["LatUnitQty_ID"]));
            }
            set {
                this["LatUnitQty_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("form#quick-receipt-entry-container > table.ko-grid.styled-ko-grid > tbody > tr:nt" +
            "h-child(1) > td:nth-child(10) > input")]
        public string VendorID_ID {
            get {
                return ((string)(this["VendorID_ID"]));
            }
            set {
                this["VendorID_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("save_btn")]
        public string SaveReceivePO_ID {
            get {
                return ((string)(this["SaveReceivePO_ID"]));
            }
            set {
                this["SaveReceivePO_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(//div[@class=\'ui-autocomplete-pagination-results\'])[1]/ul/li[1]/a")]
        public string ReceiveSupplierPO_XPATH {
            get {
                return ((string)(this["ReceiveSupplierPO_XPATH"]));
            }
            set {
                this["ReceiveSupplierPO_XPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(//div[@class=\'ui-autocomplete-pagination-results\'])[3]/ul/li[1]/a")]
        public string ReceivePOid_XPATH {
            get {
                return ((string)(this["ReceivePOid_XPATH"]));
            }
            set {
                this["ReceivePOid_XPATH"] = value;
            }
        }
    }
}
