//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBSAutomation.Locators {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Tools : global::System.Configuration.ApplicationSettingsBase {
        
        private static Tools defaultInstance = ((Tools)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Tools())));
        
        public static Tools Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("subMenuLiTools2")]
        public string ToolMenu_ID {
            get {
                return ((string)(this["ToolMenu_ID"]));
            }
            set {
                this["ToolMenu_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Create New")]
        public string CreateTool_LINK {
            get {
                return ((string)(this["CreateTool_LINK"]));
            }
            set {
                this["CreateTool_LINK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ToolID")]
        public string Tool_ID {
            get {
                return ((string)(this["Tool_ID"]));
            }
            set {
                this["Tool_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ToolType")]
        public string Tool_Type {
            get {
                return ((string)(this["Tool_Type"]));
            }
            set {
                this["Tool_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ToolLicensePlate")]
        public string ToolLicensePlate_ID {
            get {
                return ((string)(this["ToolLicensePlate_ID"]));
            }
            set {
                this["ToolLicensePlate_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AutoHomeLocation")]
        public string HomeLocation_ID {
            get {
                return ((string)(this["HomeLocation_ID"]));
            }
            set {
                this["HomeLocation_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AutoLocation")]
        public string CurrentLocation_ID {
            get {
                return ((string)(this["CurrentLocation_ID"]));
            }
            set {
                this["CurrentLocation_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ToolStatus")]
        public string ToolStatus_ID {
            get {
                return ((string)(this["ToolStatus_ID"]));
            }
            set {
                this["ToolStatus_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ImpressionCount")]
        public string ImpressionCount_ID {
            get {
                return ((string)(this["ImpressionCount_ID"]));
            }
            set {
                this["ImpressionCount_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ImpressionExpected")]
        public string ImpressionExpected_ID {
            get {
                return ((string)(this["ImpressionExpected_ID"]));
            }
            set {
                this["ImpressionExpected_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AutoSupplier")]
        public string ToolSupplier_ID {
            get {
                return ((string)(this["ToolSupplier_ID"]));
            }
            set {
                this["ToolSupplier_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PONumber")]
        public string ToolPOnumber_ID {
            get {
                return ((string)(this["ToolPOnumber_ID"]));
            }
            set {
                this["ToolPOnumber_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POCreatedDate")]
        public string POCreatedDate_ID {
            get {
                return ((string)(this["POCreatedDate_ID"]));
            }
            set {
                this["POCreatedDate_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PODate")]
        public string PODateDue_ID {
            get {
                return ((string)(this["PODateDue_ID"]));
            }
            set {
                this["PODateDue_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cost")]
        public string ToolCost_ID {
            get {
                return ((string)(this["ToolCost_ID"]));
            }
            set {
                this["ToolCost_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ReceiptNumber")]
        public string ReceiptNumber_ID {
            get {
                return ((string)(this["ReceiptNumber_ID"]));
            }
            set {
                this["ReceiptNumber_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ReceiptDate")]
        public string ReceiptDate_ID {
            get {
                return ((string)(this["ReceiptDate_ID"]));
            }
            set {
                this["ReceiptDate_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tool-purchase-external-code")]
        public string ToolGLcode_ID {
            get {
                return ((string)(this["ToolGLcode_ID"]));
            }
            set {
                this["ToolGLcode_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SupplierPurchaseDescription")]
        public string SupplierPurchaseDescription_ID {
            get {
                return ((string)(this["SupplierPurchaseDescription_ID"]));
            }
            set {
                this["SupplierPurchaseDescription_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AutoPricingType")]
        public string PricingType_ID {
            get {
                return ((string)(this["PricingType_ID"]));
            }
            set {
                this["PricingType_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AutoInvoiceCustomer")]
        public string InvoiceCustomer_ID {
            get {
                return ((string)(this["InvoiceCustomer_ID"]));
            }
            set {
                this["InvoiceCustomer_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SalesPrice")]
        public string SalesPrice_ID {
            get {
                return ((string)(this["SalesPrice_ID"]));
            }
            set {
                this["SalesPrice_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tool-sale-external-code")]
        public string SaleToolGLcode_ID {
            get {
                return ((string)(this["SaleToolGLcode_ID"]));
            }
            set {
                this["SaleToolGLcode_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AutoSaleRep")]
        public string SalesRep_ID {
            get {
                return ((string)(this["SalesRep_ID"]));
            }
            set {
                this["SalesRep_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("invoiceGen")]
        public string Invocicegeneration_ID {
            get {
                return ((string)(this["Invocicegeneration_ID"]));
            }
            set {
                this["Invocicegeneration_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("customerPO")]
        public string customerPO_ID {
            get {
                return ((string)(this["customerPO_ID"]));
            }
            set {
                this["customerPO_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CustomerInvoiceDescription")]
        public string CustomerInvoiceDescription_ID {
            get {
                return ((string)(this["CustomerInvoiceDescription_ID"]));
            }
            set {
                this["CustomerInvoiceDescription_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("save")]
        public string Save_ID {
            get {
                return ((string)(this["Save_ID"]));
            }
            set {
                this["Save_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("order")]
        public string Order_ID {
            get {
                return ((string)(this["Order_ID"]));
            }
            set {
                this["Order_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Set Existing")]
        public string SetExisting_ID {
            get {
                return ((string)(this["SetExisting_ID"]));
            }
            set {
                this["SetExisting_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cancel")]
        public string Cancel_ID {
            get {
                return ((string)(this["Cancel_ID"]));
            }
            set {
                this["Cancel_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(//div[@class=\'ui-autocomplete-pagination-results\'])[1]/ul/li[1]/a")]
        public string HomeLocationDropdown_XPATH {
            get {
                return ((string)(this["HomeLocationDropdown_XPATH"]));
            }
            set {
                this["HomeLocationDropdown_XPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(//div[@class=\'ui-autocomplete-pagination-results\'])[2]/ul/li[1]/a")]
        public string CurrLocationDropdown_XPATH {
            get {
                return ((string)(this["CurrLocationDropdown_XPATH"]));
            }
            set {
                this["CurrLocationDropdown_XPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(//div[@class=\'ui-autocomplete-pagination-results\'])[3]/ul/li[1]/a")]
        public string SupplierDropdown_XPATH {
            get {
                return ((string)(this["SupplierDropdown_XPATH"]));
            }
            set {
                this["SupplierDropdown_XPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AvailableDate")]
        public string AvailableDate_ID {
            get {
                return ((string)(this["AvailableDate_ID"]));
            }
            set {
                this["AvailableDate_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(//div[@class=\'ui-autocomplete-pagination-results\'])[4]/ul/li[1]/a")]
        public string PurchasingGLCode_XPATH {
            get {
                return ((string)(this["PurchasingGLCode_XPATH"]));
            }
            set {
                this["PurchasingGLCode_XPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(//div[@class=\'ui-autocomplete-pagination-results\'])[5]/ul/li[1]/a")]
        public string PricingTypeDropdown_XPATH {
            get {
                return ((string)(this["PricingTypeDropdown_XPATH"]));
            }
            set {
                this["PricingTypeDropdown_XPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(//div[@class=\'ui-autocomplete-pagination-results\'])[6]/ul/li[1]/a")]
        public string CustomerDropdown_XPATH {
            get {
                return ((string)(this["CustomerDropdown_XPATH"]));
            }
            set {
                this["CustomerDropdown_XPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(//div[@class=\'ui-autocomplete-pagination-results\'])[7]/ul/li[1]/a")]
        public string SalesGLDropdown_XPATH {
            get {
                return ((string)(this["SalesGLDropdown_XPATH"]));
            }
            set {
                this["SalesGLDropdown_XPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(//div[@class=\'ui-autocomplete-pagination-results\'])[8]/ul/li[1]/a")]
        public string SalesRepDropdown_XPATH {
            get {
                return ((string)(this["SalesRepDropdown_XPATH"]));
            }
            set {
                this["SalesRepDropdown_XPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("search")]
        public string ToolFilter_ID {
            get {
                return ((string)(this["ToolFilter_ID"]));
            }
            set {
                this["ToolFilter_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"tools-grid\"]/tbody/tr[2]/td[2]")]
        public string tooltable_CSS {
            get {
                return ((string)(this["tooltable_CSS"]));
            }
            set {
                this["tooltable_CSS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("recive")]
        public string Receive_ID {
            get {
                return ((string)(this["Receive_ID"]));
            }
            set {
                this["Receive_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"tools-grid\"]/tbody/tr[2]/td[8]")]
        public string ToolStatusReceive_XPATH {
            get {
                return ((string)(this["ToolStatusReceive_XPATH"]));
            }
            set {
                this["ToolStatusReceive_XPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("filterByToolName")]
        public string FilterToolID_ID {
            get {
                return ((string)(this["FilterToolID_ID"]));
            }
            set {
                this["FilterToolID_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("div.enableControlForReadAccess > div.custom-autocomplite-field > input#filterByTo" +
            "olName")]
        public string Filtertoolpage_CSS {
            get {
                return ((string)(this["Filtertoolpage_CSS"]));
            }
            set {
                this["Filtertoolpage_CSS"] = value;
            }
        }
    }
}
